#!/bin/bash -e
if [ "$1" = "" ]; then
  echo Usage: makedeb VERSION
  exit 1
fi

VERSION="$1"
TMP_TAR="/tmp/zeroinstall-injector-$VERSION.tar"

if [ ! -e "$TMP_TAR.bz2" ]; then
  echo Missing: $TMP_TAR.bz2
  exit 1
fi

orig="zeroinstall-injector_$VERSION.orig.tar"

echo "Copying $TMP_TAR.bz2 as $orig.gz..."

rm -rf "source-$VERSION" "binary-$VERSION"
mkdir "source-$VERSION"
cp "$TMP_TAR.bz2" "source-$VERSION/$orig.bz2"
# See http://doc.ubuntu.com/ubuntu/packagingguide/C/basic-mistakes.html
(cd source-$VERSION && bunzip2 "$orig.bz2" && gzip -9 "$orig")

(cd "source-$VERSION" &&
 tar xzf "$orig.gz" &&
 cd "zeroinstall-injector-$VERSION" &&
 #patch -p1 < ../../report-error.patch
 cp -r ../../debian .)

echo Building binary...
cp -r "source-$VERSION" "binary-$VERSION"
(cd "binary-$VERSION/zeroinstall-injector-$VERSION" &&
 dpkg-buildpackage -kTesting -rfakeroot)

echo Building source...
cd "source-$VERSION/zeroinstall-injector-$VERSION"
if [ "$2" = "--test" ]; then
  dpkg-buildpackage -S -sa -kTesting -rfakeroot
else
  dpkg-buildpackage -S -sa -k59A53CC1 -rfakeroot
fi

echo Running lintian...
lintian -i ../*.changes || echo Lintian failed

echo Hint:
echo cd "source-$VERSION"
echo dupload -t mentors *_source.changes
