#!/bin/bash -e
if [ "$1" = "" ]; then
  echo Usage: makedeb VERSION
  exit 1
fi

VERSION="$1"
TMP_TAR="/tmp/zeroinstall-injector-$VERSION.tar.gz"

if [ ! -e "$TMP_TAR" ]; then
  echo Missing: $TMP_TAR
  exit 1
fi

orig="zeroinstall-injector_$VERSION.orig.tar.gz"

echo "Copying $TMP_TAR as $orig..."

rm -rf "source-$VERSION" "binary-$VERSION"
mkdir "source-$VERSION"
cp "$TMP_TAR" "source-$VERSION/$orig"

(cd "source-$VERSION" &&
 tar xzf "$orig" &&
 cd "zeroinstall-injector-$VERSION" &&
 #patch -p0 < ../../desktop-install.patch
 cp -r ../../debian .)

echo Building binary...
cp -r "source-$VERSION" "binary-$VERSION"
(cd "binary-$VERSION/zeroinstall-injector-$VERSION" &&
 dpkg-buildpackage -kTesting -rfakeroot)

echo Building source...
cd "source-$VERSION/zeroinstall-injector-$VERSION"
if [ "$2" = "--test" ]; then
  dpkg-buildpackage -S -sa -kTesting -rfakeroot
else
  dpkg-buildpackage -S -sa -k59A53CC1 -rfakeroot
fi

echo Running lintian...
lintian -i ../*.changes

echo Hint:
echo cd "source-$VERSION"
echo '(untested)'
echo dupload -t mentors *_source.changes
