#!/bin/sh -eux
dpkg -i *.deb
0install config help_with_testing true
0install add 0test http://0install.net/2008/interfaces/0test.xml
echo SKIPPING BROKEN TESTS
#0test http://0install.net/2008/interfaces/0test.xml 0.10
